name: Deploy GCP Storage Bucket with Terraform

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.0

      - name: Log in to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
 
      - name: Install gke-gcloud-auth-plugin
        run: |
          sudo apt-get update
          sudo apt-get install -y google-cloud-sdk-gke-gcloud-auth-plugin

      - name: Initialize Terraform
        run: terraform init terraform

      - name: Plan Terraform deployment
        run: terraform plan -var="credentials=${{ secrets.GCP_SA_KEY }}" -var="project_id=empyrean-bridge-426118-q3" -var="region=us-central1" -var="bucket_name=web-123@" terraform

      - name: Apply Terraform changes
        run: terraform apply -auto-approve -var="credentials=${{ secrets.GCP_SA_KEY }}" -var="project_id=empyrean-bridge-426118-q3" -var="region=us-central1" -var="bucket_name=web-123@" terraform

      - name: Show Terraform outputs
        run: terraform output -json

      - name: Clean up Terraform files
        run: rm -rf .terraform terraform.tfstate*

      - name: Validate GCP Storage Bucket deployment
        run: |
          bucket_url=$(terraform output -json | jq -r .bucket_url.value)
          curl -sI $bucket_url | head -n 1 | grep "200 OK"
